name: Test and Build Docker for CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
      
env:
  IMAGE_NAME: CS333Final-Image

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ${{ env.IMAGE_NAME }}      

    - name: Push Docker image
      run: docker push ${{ env.IMAGE_NAME }}
        
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and test Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.IMAGE_NAME }}:latest --load .
        docker run -it --rm ${{ env.IMAGE_NAME }} python -m unittest discover tests


