name: Test and Build Docker for CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
      
env:
  IMAGE_NAME: CS333Final-Image


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      run:
        python -m unittest discover
        coverage run TestUnitDriver.py
        coverage report