name: Test and Build Docker for CI


on: [push]


jobs:   
  testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3
        
    - name: Install dependencies
      run: 
        python -m pip install --upgrade pip
        pip install unittest
        pip install coverage
        
    - name: Run tests
      run:
        python3 -m unittest TestDriver.py
        coverage run TestDriver.py
        coverage report


  env:
    IMAGE_NAME: CS333Final-Image

  build image:
    runs-on: ubuntu-latest
    needs: testing
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/chess:latest